Reduce sqlite3.js build size by about 30kb by stripping out Emscripten's makeInvalidEarlyAccess() wrappers.
FossilOrigin-Name: a65bd978cbc646ec687ebcfc736a968e0597062251b2155caab42bca2d36f1e9

diff --git a/ext/wasm/GNUmakefile b/ext/wasm/GNUmakefile
--- a/ext/wasm/GNUmakefile
+++ b/ext/wasm/GNUmakefile
@@ -513,8 +513,9 @@ endif
 # generate an Emscripten module and where $@ is the module's .js/.mjs
 # file.
 SQLITE.strip-createExportWrapper = \
-  sed -i -e '/^.*= \(_sqlite3\|_fiddle\)[^=]* = createExportWrapper/d' $@ || exit; \
-  echo '(Probably) stripped out extraneous createExportWrapper() parts.'
+  sed -i -e '/^.*= \(_sqlite3\|_fiddle\)[^=]*=.*createExportWrapper/d' \
+  -e '/^var \(_sqlite3\|_fiddle\)[^=]*=.*makeInvalidEarlyAccess/d' $@ || exit; \
+  echo '(Probably) stripped out createExportWrapper() and makeInvalidEarlyAccess() parts.'
 
 # When passing emcc_opt from the CLI, += and re-assignment have no
 # effect, so emcc_opt+=-g3 doesn't work. So...
